name: Deploy Python Script
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add SSH Host Key
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Set script path
        run: |
          echo "SCRIPT_PATH=/home/${{ secrets.SSH_USER }}" >> $GITHUB_ENV
          
      - name: Transfer Python Script and requirements.txt
        run: |
          scp bot2.py requirements.txt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/
          
      - name: Run Python Script on Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            # Navigate to the home directory
            cd ~
            
            # Set up the virtual environment
            python3 -m venv venv
            
            # Activate the virtual environment
            source venv/bin/activate
            
            # Install the dependencies from requirements.txt
            pip install -r requirements.txt
            
            # Run the Python script inside the venv
            python bot2.py
            
            # Optionally deactivate the venv after running
            deactivate
          EOF
