name: Deploy Python Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use a self-hosted runner if preferred

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Set the default script path if not provided
      - name: Set script path
        run: |
          echo "SCRIPT_PATH=${{ secrets.SCRIPT_PATH }}${{ secrets.SCRIPT_PATH == '' && '/home/' || '/home/' + secrets.SSH_USER }}" >> $GITHUB_ENV

      # Step 4: Transfer the Python script to the server
      - name: Transfer Python Script
        run: |
          scp my_script.py ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$SCRIPT_PATH

      # Step 5: Execute the Python script on the server
      - name: Run Python Script on Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd $SCRIPT_PATH
            python3 my_script.py
          EOF
