name: Deploy Python Script
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add SSH Host Key
        run: |
          ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Set script path
        run: |
          echo "SCRIPT_PATH=/home/${{ secrets.SSH_USER }}" >> $GITHUB_ENV
          
      - name: Transfer Python Script
        run: |
          scp -P ${{ secrets.SSH_PORT }} bot2.py requirements.txt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/
          
      - name: Run Python Script on Server
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ~
            
            pkill -f "python bot2.py" || true

            python3 -m venv venv
            
            source venv/bin/activate
            
            pip install -r requirements.txt
            
            nohup bash -c "TOKEN=${{ secrets.BOT_TOKEN }} python bot2.py > bot2.log 2>&1 &"

            sleep 7
            cat bot2.log
            
            deactivate
          EOF
