name: Deploy Python Script

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Transfer the Python script to the server
      - name: Transfer Python Script
        run: |
          scp my_script.py ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SCRIPT_PATH:-/home/${{ secrets.SSH_USER }}/}}

      # Step 4: Execute the script or restart the service on the server
      - name: Restart Service or Run Script
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ${{ secrets.SCRIPT_PATH:-/home/${{ secrets.SSH_USER }}/}}
          python3 my_script.py
          EOF
