name: Deploy Python Script
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Set script path
        run: |
          if [ -z "${{ secrets.SCRIPT_PATH }}" ]; then
            echo "SCRIPT_PATH=/home/" >> $GITHUB_ENV
          else
            echo "SCRIPT_PATH=/home/${{ secrets.SSH_USER }}" >> $GITHUB_ENV
          fi
          
      - name: Transfer Python Script
        run: |
          scp my_script.py ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$SCRIPT_PATH
          
      - name: Run Python Script on Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd $SCRIPT_PATH
            python3 my_script.py
          EOF
